FROM node:18-bullseye-slim

ENV WORK=/opt/hsl-map-server
ENV DATA_DIR=${WORK}/data
ENV NODE_OPTS ""
ENV NODE_ENV=production

# Debian bullseye is EOL; deb.debian.org's live bullseye/bullseye-security
# repos have rotated forward and now conflict with package versions already
# baked into this base image (e.g. libc6, perl-base, libudev1), and
# bullseye-security's Release file has also started expiring. Pin apt to a
# fixed snapshot.debian.org date that is consistent with this image instead.
RUN printf 'deb http://snapshot.debian.org/archive/debian/20250520T000000Z bullseye main\ndeb http://snapshot.debian.org/archive/debian-security/20250520T000000Z bullseye-security main\ndeb http://snapshot.debian.org/archive/debian/20250520T000000Z bullseye-updates main\n' > /etc/apt/sources.list \
  && apt-get update -o Acquire::Check-Valid-Until=false \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y wget ca-certificates xserver-xorg-video-dummy libjemalloc2 \
  # maplibre-native dependencies
  ccache cmake ninja-build pkg-config xvfb libcurl4-openssl-dev libglfw3-dev libuv1-dev g++-10 libc++-9-dev libc++abi-9-dev libpng-dev libgl1-mesa-dev libgl1-mesa-dri --no-install-recommends \
  && wget http://archive.ubuntu.com/ubuntu/pool/main/libj/libjpeg-turbo/libjpeg-turbo8_2.0.3-0ubuntu1_amd64.deb \
  && apt install ./libjpeg-turbo8_2.0.3-0ubuntu1_amd64.deb \
  && wget http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu66_66.1-2ubuntu2_amd64.deb \
  && apt install ./libicu66_66.1-2ubuntu2_amd64.deb \
  && rm ./*.deb \
  && rm -rf /var/lib/apt/lists/*

# This should prevent memory leak of sharp-package
ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2

RUN mkdir -p ${WORK}
WORKDIR ${WORK}

COPY yarn.lock package.json ${WORK}/
RUN yarn install && yarn cache clean

COPY . ${WORK}

RUN mkdir -p ${DATA_DIR}

# OpenMapTiles dataset generated by hsldevcom
RUN wget https://hslstoragekarttatuotanto.blob.core.windows.net/openmaptiles/tiles.mbtiles -q -t 3 -O ${DATA_DIR}/finland.mbtiles

EXPOSE 8080

CMD \
  (Xorg -dpi 96 -nolisten tcp -noreset +extension GLX +extension RANDR +extension RENDER -logfile ./10.log -config ./xorg.conf :10 & \
  DISPLAY=":10" yarn forever start --spinSleepTime 60000 --minUptime 30000 -c "node ${NODE_OPTS}" \
    node_modules/tessera/bin/tessera.js --port 8080 --config config.js --multiprocess \
      -r ${WORK}/node_modules/tilelive-gl/ \
      -r ${WORK}/node_modules/tilelive-geojson && \
  yarn forever --fifo logs 0)
