name: Process dev push or pr
on:
  schedule:
   - cron:  '45 0 * * *'
  push:
    branches:
      - develop
jobs:
  docker-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop
      - name: Change permissions
        run: chmod +x ./.github/workflows/scripts/build_and_push_image.sh
      - name: Build docker image from dev and push it
        run: ./.github/workflows/scripts/build_and_push_image.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_AUTH: ${{ secrets.DOCKER_AUTH }}
          DOCKER_TAG: dev
