name: Process next-prod push or pr
on:
  schedule:
    - cron:  '0 4 * * *'
  push:
    branches:
      - next-prod
  pull_request:
    branches:
      - next-prod
jobs:
  docker-push:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Change permissions
        run: chmod +x ./.github/workflows/scripts/build_and_push_next-prod.sh
      - name: Build docker image from next-prod and push it
        run: ./.github/workflows/scripts/build_and_push_next-prod.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_AUTH: ${{ secrets.DOCKER_AUTH }}
          FONTSTACK_PASSWORD: ${{ secrets.FONTSTACK_PASSWORD }}
          DOCKER_TAG: next-prod