name: Process master push or pr
on:
  schedule:
    - cron:  45 1 * * *
  push:
    branches:
      - master
jobs:
  docker-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Change permissions
        run: chmod +x ./.github/workflows/scripts/build_and_push_image.sh
      - name: Build docker image from master and push it
        run: ./.github/workflows/scripts/build_and_push_image.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_AUTH: ${{ secrets.DOCKER_AUTH }}
          DOCKER_TAG: prod
