name: Process master push or pr
on:
  schedule:
    - cron:  0 2 * * *
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  docker-push:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Change permissions
        run: chmod +x ./.github/workflows/scripts/build_and_push_prod.sh
      - name: Build docker image from master and push it
        run: ./.github/workflows/scripts/build_and_push_prod.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_AUTH: ${{ secrets.DOCKER_AUTH }}
          FONTSTACK_PASSWORD: ${{ secrets.FONTSTACK_PASSWORD }}
          DOCKER_TAG: prod
